### ISSUE TITLE
Unable to make calls from browser (giving exception: Web phone unavailable)

### ISSUE THREAD

**Issue by Tonyabott** [ringcentral/ringcentral-embeddable-voice#107]
Hi @embbnux
Thanks for your support.

We started integrating RingCentral Embeddable Voice in our application.

Now we are getting an issue like 'Web Phone Unavailable'. We are using the same key's (APP - API key and Secret) what we tested in given demo. Its working fine in Demo where as it giving exception in the integrated app.

Can you please help us to overcome this issue.
![2018-05-16](https://user-images.githubusercontent.com/34772600/40121276-d0104012-593e-11e8-98b6-a49a7e286591.png)

We are allowing audio and micro phone permissions as well, but still its throwing same exception.

**Comment by embbnux** [comment]
Hi, @Tonyabott Can you check audio permission in Settings -> AudioSettings page.

**Comment by Tonyabott** [comment]
Hi @embbnux,
Verified the settings and allowed the permissions.

If we use iframe, then we are facing this issue. Where as it works fine if we use the given script.

Thanks

**Comment by embbnux** [comment]
Do you add `allow="microphone"` in iframe?  It makes browser to allow iframe to use microphone.

**Comment by Tonyabott** [comment]
Hi @embbnux 

Thanks for the support. It works. 
Any way we opt to use script instead of iframe.

And we want to use Ring Central API's along with 'Embeddable Voice'. So, can we call the Ring Central API's with out any further authentication. (As we already authenticated with embeddable voice.). If yes where can we get access token in order to send it in header while calling API's.



Thanks in Advance.

**Comment by embbnux** [comment]
@Tonyabott This is a demo that shows how to get access token from redirect uri.   https://github.com/embbnux/ringcentral-web-widget-demo

1. You need to configure Embeddable Voice to use your redirect uri.  https://github.com/ringcentral/ringcentral-embeddable-voice/blob/master/docs/customize-redirect-uri.md
2. Set Embeddable Voice to use your own ringcentral app client id. And please use implicit grant(don't pass client secret) https://github.com/ringcentral/ringcentral-embeddable-voice/blob/master/docs/config-client-id-and-secret.md
3. You can get access token from redirect page and pass it to Embeddable Voice.

**Comment by Tonyabott** [comment]
Hi @embbnux 

Can you please tell us, how we need to pass the access token to Embeddable Voice.

Thanks.

**Comment by embbnux** [comment]
Hi, @Tonyabott Just in redirect page, add following codes:
```
<script>
  if (window.opener) {
    window.opener.postMessage({
      callbackUri: window.location.href,
    }, '*');
  }
</script>
```
Embeddable Voice can get it from `postMesssage`.
https://github.com/ringcentral/ringcentral-embeddable-voice/blob/master/docs/customize-redirect-uri.md

**Comment by Tonyabott** [comment]
Hi @embbnux 
1. 
function checkLoign() {
      setTimeout(function () {
        platform.loggedIn().then(function(logined) {
          if (logined) {
            console.log('ringcentral platform logined');
            subscription.setEventFilters(['/account/~/extension/~/presence?detailedTelephonyState=true']).register();
            subscription.on(subscription.events.notification, function(msg) {
              console.log('notification:', msg);
              if (msg.event.indexOf('presence?detailedTelephonyState=true') > -1) {
                var endedCalls = msg.body.activeCalls.filter(function(call) {
                  return call.telephonyStatus === 'NoCall';
                });
                getCallLogs(endedCalls);
              }
            });
          } else {
            checkLoign();
          }
        })
      }, 2000);
    }


it Prints "'ringcentral platform logined'" in the console.
But doesn't print any call logs not even executes console.log('notification:', msg);



2. And when a call ends, do we get notified (through webhook or any other way) in order to maintain the call log in our DB?

Thanks.

**Comment by embbnux** [comment]
Hi, @Tonyabott `Account Presence Event` doesn't support `detailedTelephonyState`, please use `/account/{accountId}/presence` to listen account level presence. 
For call notification, you can get it by `/account/~/extension/~/presence?detailedTelephonyState=true` in extension user level.  
Following is detailed document about notification event. https://developer.ringcentral.com/api-docs/latest/index.html#!#RefGetExtensionPresenceEvent

**Comment by embbnux** [comment]
Actually for call notification, I think you can just listen to Embeddable Voice [active call event](https://github.com/ringcentral/ringcentral-embeddable-voice/blob/master/docs/widget-event.md#active-call-event), it is data from `/account/~/extension/~/presence?detailedTelephonyState=true`.
For sms event, we are planning to add sms event in Embeddable Voice. So you don't need to require it from RingCentral API.

**Comment by Tonyabott** [comment]
Hi, @embbnux 
Thanks, That's a good thing. 
Please let us know when can we have the sms event in Embeddable Voice?
And also is there any other option to fetch the sms log to know whether the sms has been sent successfully and to read incoming messages?

**Comment by embbnux** [comment]
@Tonyabott The message event is available now https://github.com/ringcentral/ringcentral-embeddable-voice/blob/master/docs/widget-event.md#message-event
