### ISSUE TITLE
add Desktop Notification in adapter

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-embeddable-voice#15]
pop up a notification when there is a new call

**Comment by AndyHaas** [comment]
How hard is this enhancement? I am attempting do a web based pop up but not having any such luck to pass the parameters to answer and hang up/reject the call.

**Comment by embbnux** [comment]
Hi, @AndyHaas It isn't hard to do this.  I will start to work on this after I finished [messages enhancement](https://github.com/ringcentral/ringcentral-embeddable-voice/issues/56).
And you can also support this out of the widget by yourself.  You can listen to [web phone event](https://github.com/ringcentral/ringcentral-embeddable-voice/blob/master/docs/widget-event.md#web-phone-call-event) and use [call API](https://github.com/ringcentral/ringcentral-embeddable-voice/blob/master/docs/control-widget.md#control-the-web-call) to hang up/reject
