### ISSUE TITLE
Keypad Lookup by name

### ISSUE THREAD

**Issue by AndyHaas** [ringcentral/ringcentral-embeddable-voice#33]
Currently you can only type in a phone number. It would be nice like how the text messaging, you can type in a name and text that person. But in this instance it would be calling the person

**Comment by embbnux** [comment]
@AndyHaas  Thanks for your great idea. Actually the feature is in our backlog. I will keep it updated with you when it is added.

**Comment by embbnux** [comment]
- [ ] search contacts on keypad

**Comment by AndyHaas** [comment]
This needs to be included for transferring calls also

**Comment by AndyHaas** [comment]
Transfer to page still needs Lookup by Name or Number
![image](https://user-images.githubusercontent.com/22582720/34158758-50b84336-e48c-11e7-9c2a-a527fda7b075.png)

**Comment by embbnux** [comment]
Transfer with contact searching will come soon.

**Comment by embbnux** [comment]
Transfer with contact searching is finished

**Comment by AndyHaas** [comment]
Closing issue. I have tested and verified all is working
