### ISSUE TITLE
SMS Retrieve previous messages/conversations

### ISSUE THREAD

**Issue by AndyHaas** [ringcentral/ringcentral-embeddable-voice#56]
When you are in the web widget, message tab.  Any previous messages/conversations that you have may sent out via your cell phone or other apps do not get pulled in.

**Comment by embbnux** [comment]
Hi, @AndyHaas Now the app only pulls messages in recent 7 days. We will create a enhancement to support to pull older message.

Does you get messages in recent 7 days? If you don't get, please let's know. it may be a bug.

**Comment by AndyHaas** [comment]
@embbnux the app does currently get the last 7 days of messages. When we convert over from the desktop app to the web widget I am trying to eliminate the calls of "Where are my messages"

**Comment by LingForCC** [comment]
@AndyHaas

**Comment by AndyHaas** [comment]
suggestion is when they scroll all the way at the top is to have a button that states to get the previous messages. and they can continue to scroll up and get the older messages

**Comment by embbnux** [comment]
Thanks @AndyHaas  Good idea, it has been in our backlog

**Comment by AndyHaas** [comment]
Would like to see this get accomplished. I am using this a day to day tool and have to keep going to my cell phone to see previous texts. If there is any way to update this to allow a end user to grab previous messages this would make life a bit easier.

**Comment by embbnux** [comment]
@AndyHaas I will push this. Thanks

**Comment by AndyHaas** [comment]
@embbnux this looks good. I was able to go all the way back to the begging of time. Much appreciated.
