### ISSUE TITLE
Display times when texts were received  

### ISSUE THREAD

**Issue by AndyHaas** [ringcentral/ringcentral-embeddable-voice#76]
When a text comes in on the web app I do not see when that text message comes in. Please display when that time cam in. Example of android phone app with what I am looking for. 

![image](https://user-images.githubusercontent.com/22582720/34906606-5772e150-f836-11e7-9ac0-01c3ed22f484.png)

![image](https://user-images.githubusercontent.com/22582720/34906607-5b13eac0-f836-11e7-9ac9-7bd84acc90a4.png)

**Comment by AndyHaas** [comment]
@embbnux looks on the staging you have added the time variable also. I have looked at this and the time is showing when necessary.

**Comment by embbnux** [comment]
Yes, It's added
