### ISSUE TITLE
Getting authorization error 400

### ISSUE THREAD

**Issue by Tonyabott** [ringcentral/ringcentral-embeddable-voice#97]
Getting below error after click on authorise,  can you please help me what i'm doing wrong.

```json
{
  "error" : "invalid_client",
  "error_description" : "[ThirdPartyAppAccess] permission required",
  "errors" : [ {
    "errorCode" : "CMN-408",
    "message" : "[ThirdPartyAppAccess] permission required",
    "parameters" : [ {
      "parameterName" : "permissionName",
      "parameterValue" : "ThirdPartyAppAccess"
    } ]
  } ]
}
```

Thanks in advance.

**Comment by embbnux** [comment]
Hi, @Tonyabott Are you using RingCentral developer account to log into RingCentral Embeddable Voice?  

The RingCentral free account created from RingCentral Developer Website don't have permission to log into third party app on production environment. The Embeddable Voice is developed as a third party integration app.

If you just want to test RingCentral Embeddable Voice Widget, you can turn this app to sandbox environment, and login with your sandbox account Which created in RingCentral Development Website when you create a RingCentral app. Following is steps to set sandbox environment:

1. Go to https://ringcentral.github.io/ringcentral-embeddable-voice/
2.
![1911522420209_ pic_hd](https://user-images.githubusercontent.com/7036536/38141370-594fd6c0-346a-11e8-9e31-db8a70729798.jpg)
3. 
![1921522420288_ pic_hd](https://user-images.githubusercontent.com/7036536/38141375-63dc4e8e-346a-11e8-8fba-d45d1ff33d50.jpg)
4. Log in with sandbox account

**Comment by Tonyabott** [comment]
Hi @embbnux , thanks for the quick reply.

Can we make calls from browser in sandbox environment?

**Comment by AndyHaas** [comment]
@Tonyabott, You can make calls but you are unable to send SMS.

**Comment by Tonyabott** [comment]
@AndyHaas I followed the steps given by you, nothing happening when click on call button after entering the number. It prompts me to open RingCentral for Mac.

![screen shot 2018-04-02 at 9 19 06 pm](https://user-images.githubusercontent.com/34772600/38203101-abc7588a-36bb-11e8-9a14-0b0613ef8110.png)

Thanks In Advance.

**Comment by AndyHaas** [comment]
Go into Settings and change the setting to Make my calls with to Browser

**Comment by Tonyabott** [comment]
Yes, changed the settings and also have the permissions.

![screen shot 2018-04-03 at 1 00 07 pm](https://user-images.githubusercontent.com/34772600/38235658-7fb029a0-373f-11e8-8354-e30ae9d8f26a.png)


got the below warning when click on call button "Your extension is not allowed to make outbound calls with browser currently, please contact your account representative for an upgrade." Is this is due to sandbox mode?

Thanks

**Comment by embbnux** [comment]
Hi, @Tonyabott In browser web phone mode, it requires a Digital Line in your account. You need to add a phone in your sandbox account. Please visit `https://service.devtest.ringcentral.com` to add a Phone to your sandbox account.

**Comment by Tonyabott** [comment]
Thanks @embbnux, I got that. Now i'm able to make calls from browser.

**Comment by embbnux** [comment]
Closed by resolved

**Comment by Tonyabott** [comment]
Hi @embbnux 
Thanks for your support.

We started integrating RingCentral Embeddable Voice in our application.

Now we are getting an issue like 'Web Phone Unavailable'. We are using the same key's (APP - API key and Secret) what we tested in given demo. Its working fine in Demo where as it giving exception in the integrated app.

Can you please help us to overcome this issue.
![2018-05-16](https://user-images.githubusercontent.com/34772600/40121031-3a7fe796-593e-11e8-9986-6a7acccef545.png)


We are allowing audio and micro phone permissions as well, but still its throwing same exception.

**Comment by JiandongRuan** [comment]
I am hitting the same issue. But when I tried to create the "RingCentral for Desktop" device, I was asked to assign a number to the device. "Select Existing Number" button was disabled and "New Number" isn't free. How can I test the embeddable using developer account?

**Comment by embbnux** [comment]
@JiandongRuan Can you provide more information how you hit this issue.
Are you using your own RingCentral app client id?  And is your app client id private?
